
from typing import Literal

# 从配置文件 ftp_registers.py 自动生成的寄存器名称Literal类型
RegisterName = Literal["HAND_ID", "REDU_RATIO", "CLEAR_ERROR", "SAVE", "RESET_PARA", "GESTURE_FORCE_CALIB", "DEFAULT_SPEED_SET(0)", "DEFAULT_SPEED_SET(1)", "DEFAULT_SPEED_SET(2)", "DEFAULT_SPEED_SET(3)", "DEFAULT_SPEED_SET(4)", "DEFAULT_SPEED_SET(5)", "DEFAULT_FORCE_SET(0)", "DEFAULT_FORCE_SET(1)", "DEFAULT_FORCE_SET(2)", "DEFAULT_FORCE_SET(3)", "DEFAULT_FORCE_SET(4)", "DEFAULT_FORCE_SET(5)", "POS_SET(0)", "POS_SET(1)", "POS_SET(2)", "POS_SET(3)", "POS_SET(4)", "POS_SET(5)", "ANGLE_SET(0)", "ANGLE_SET(1)", "ANGLE_SET(2)", "ANGLE_SET(3)", "ANGLE_SET(4)", "ANGLE_SET(5)"]

# 所有寄存器名称列表
ALL_REGISTER_NAMES: list[RegisterName] = ["HAND_ID", "REDU_RATIO", "CLEAR_ERROR", "SAVE", "RESET_PARA", "GESTURE_FORCE_CALIB", "DEFAULT_SPEED_SET(0)", "DEFAULT_SPEED_SET(1)", "DEFAULT_SPEED_SET(2)", "DEFAULT_SPEED_SET(3)", "DEFAULT_SPEED_SET(4)", "DEFAULT_SPEED_SET(5)", "DEFAULT_FORCE_SET(0)", "DEFAULT_FORCE_SET(1)", "DEFAULT_FORCE_SET(2)", "DEFAULT_FORCE_SET(3)", "DEFAULT_FORCE_SET(4)", "DEFAULT_FORCE_SET(5)", "POS_SET(0)", "POS_SET(1)", "POS_SET(2)", "POS_SET(3)", "POS_SET(4)", "POS_SET(5)", "ANGLE_SET(0)", "ANGLE_SET(1)", "ANGLE_SET(2)", "ANGLE_SET(3)", "ANGLE_SET(4)", "ANGLE_SET(5)"]
